-- =====================================================================
--  Student Organization Event Registration and Attendance System
--  PostgreSQL schema + demo data
--
--  1) Create the database once (psql or pgAdmin):
--         CREATE DATABASE student_event_db;
--  2) Run this script against it:
--         psql -U postgres -d student_event_db -f Database/student_event_db.sql
--
--  WARNING: re-running this script DROPS and recreates all tables (data is reset).
--
--  Names are snake_case to match EF Core's UseSnakeCaseNamingConvention()
--  (see AsiBasecodeDBContext). Enum columns store the enum name as text.
--
--  Demo accounts (password in parentheses):
--      admin     (Admin@123)    - Admin
--      msantos   (Officer@123)  - Officer, President of CSS
--      jreyes    (Officer@123)  - Officer, Governor of ESC
--      student1..student6 (Student@123) - Students
-- =====================================================================

BEGIN;

DROP TABLE IF EXISTS attendances CASCADE;
DROP TABLE IF EXISTS event_registrations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS organization_members CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ---------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------

CREATE TABLE users (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         varchar(50)  NOT NULL,
    name            varchar(100) NOT NULL,
    email           varchar(100),
    student_number  varchar(20),
    course          varchar(100),
    year_level      integer,
    role            varchar(20)  NOT NULL DEFAULT 'Student',
    is_active       boolean      NOT NULL DEFAULT true,
    password        varchar(255) NOT NULL,
    created_by      varchar(50)  NOT NULL,
    created_time    timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(50)  NOT NULL,
    updated_time    timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_user_id UNIQUE (user_id),
    CONSTRAINT uq_users_student_number UNIQUE (student_number),
    CONSTRAINT ck_users_role CHECK (role IN ('Admin', 'Officer', 'Student')),
    CONSTRAINT ck_users_year_level CHECK (year_level IS NULL OR year_level BETWEEN 1 AND 6)
);

CREATE TABLE organizations (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(150)  NOT NULL,
    acronym         varchar(20),
    description     varchar(1000),
    adviser         varchar(100),
    is_active       boolean       NOT NULL DEFAULT true,
    created_by      varchar(50)   NOT NULL,
    created_time    timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(50)   NOT NULL,
    updated_time    timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_organizations_name UNIQUE (name)
);

CREATE TABLE organization_members (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id integer     NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    member_id       integer     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    position        varchar(50),
    joined_time     timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_organization_members UNIQUE (organization_id, member_id)
);

CREATE TABLE events (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       integer       NOT NULL REFERENCES organizations (id) ON DELETE RESTRICT,
    title                 varchar(150)  NOT NULL,
    description           varchar(2000),
    venue                 varchar(150)  NOT NULL,
    start_time            timestamp without time zone NOT NULL,
    end_time              timestamp without time zone NOT NULL,
    registration_deadline timestamp without time zone NOT NULL,
    capacity              integer       NOT NULL DEFAULT 0,
    late_after_minutes    integer       NOT NULL DEFAULT 15,
    status                varchar(20)   NOT NULL DEFAULT 'Draft',
    created_by            varchar(50)   NOT NULL,
    created_time          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(50)   NOT NULL,
    updated_time          timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_events_status CHECK (status IN ('Draft', 'Open', 'Closed', 'Completed', 'Cancelled')),
    CONSTRAINT ck_events_schedule CHECK (end_time > start_time),
    CONSTRAINT ck_events_deadline CHECK (registration_deadline <= start_time),
    CONSTRAINT ck_events_capacity CHECK (capacity >= 0),
    CONSTRAINT ck_events_late CHECK (late_after_minutes >= 0)
);
CREATE INDEX ix_events_start_time ON events (start_time);
CREATE INDEX ix_events_organization_id ON events (organization_id);

CREATE TABLE event_registrations (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          integer     NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    student_id        integer     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    registration_code varchar(32) NOT NULL,
    status            varchar(20) NOT NULL DEFAULT 'Registered',
    registered_time   timestamp without time zone NOT NULL DEFAULT now(),
    cancelled_time    timestamp without time zone,
    CONSTRAINT uq_event_registrations_event_student UNIQUE (event_id, student_id),
    CONSTRAINT uq_event_registrations_code UNIQUE (registration_code),
    CONSTRAINT ck_event_registrations_status CHECK (status IN ('Registered', 'Waitlisted', 'Cancelled'))
);
CREATE INDEX ix_event_registrations_student_id ON event_registrations (student_id);

CREATE TABLE attendances (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id integer     NOT NULL REFERENCES event_registrations (id) ON DELETE CASCADE,
    check_in_time   timestamp without time zone,
    check_out_time  timestamp without time zone,
    status          varchar(20) NOT NULL,
    remarks         varchar(250),
    recorded_by     varchar(50) NOT NULL,
    recorded_time   timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendances_registration UNIQUE (registration_id),
    CONSTRAINT ck_attendances_status CHECK (status IN ('Present', 'Late', 'Absent'))
);

-- ---------------------------------------------------------------------
-- Demo data (dates are relative to when the script runs)
-- Passwords are AES-encrypted with PasswordManager and the SecretKey in appsettings.json.
-- ---------------------------------------------------------------------

INSERT INTO users (id, user_id, name, email, student_number, course, year_level, role, is_active, password, created_by, updated_by) VALUES
 (1, 'admin',    'System Administrator', 'admin@school.edu',    NULL,         NULL,                              NULL, 'Admin',   true, '0oGwxqqIMRkUY18Gmo8ygw==', 'sys', 'sys'),
 (2, 'msantos',  'Maria Santos',         'msantos@school.edu',  '2022-10001', 'BS Computer Science',             4,    'Officer', true, 'Bzwl+bhyITd9xUcAclUGiQ==', 'sys', 'sys'),
 (3, 'jreyes',   'Jose Reyes',           'jreyes@school.edu',   '2022-10002', 'BS Civil Engineering',            4,    'Officer', true, 'Bzwl+bhyITd9xUcAclUGiQ==', 'sys', 'sys'),
 (4, 'student1', 'Ana Cruz',             'acruz@school.edu',    '2024-20001', 'BS Computer Science',             2,    'Student', true, 'yCu8wa23pxcND4LfRFKf4A==', 'sys', 'sys'),
 (5, 'student2', 'Mark Villanueva',      'mvillanueva@school.edu', '2024-20002', 'BS Information Technology',   2,    'Student', true, 'yCu8wa23pxcND4LfRFKf4A==', 'sys', 'sys'),
 (6, 'student3', 'Liza Garcia',          'lgarcia@school.edu',  '2023-20003', 'BS Civil Engineering',            3,    'Student', true, 'yCu8wa23pxcND4LfRFKf4A==', 'sys', 'sys'),
 (7, 'student4', 'Paolo Mendoza',        'pmendoza@school.edu', '2025-20004', 'BS Computer Science',             1,    'Student', true, 'yCu8wa23pxcND4LfRFKf4A==', 'sys', 'sys'),
 (8, 'student5', 'Grace Tan',            'gtan@school.edu',     '2023-20005', 'AB Communication',                3,    'Student', true, 'yCu8wa23pxcND4LfRFKf4A==', 'sys', 'sys'),
 (9, 'student6', 'Carlo Ramos',          'cramos@school.edu',   '2024-20006', 'BS Information Technology',       2,    'Student', true, 'yCu8wa23pxcND4LfRFKf4A==', 'sys', 'sys');

INSERT INTO organizations (id, name, acronym, description, adviser, is_active, created_by, updated_by) VALUES
 (1, 'Computer Science Society',    'CSS', 'Academic organization of Computer Science and IT students.', 'Prof. Ramon Dizon',   true, 'admin', 'admin'),
 (2, 'Engineering Student Council', 'ESC', 'Student government of the College of Engineering.',         'Engr. Teresa Lim',    true, 'admin', 'admin'),
 (3, 'Arts and Culture Club',       'ACC', 'Promotes arts, music and cultural heritage on campus.',       'Ms. Patricia Aquino', true, 'admin', 'admin');

INSERT INTO organization_members (organization_id, member_id, position) VALUES
 (1, 2, 'President'),
 (1, 4, 'Member'),
 (1, 7, 'Member'),
 (2, 3, 'Governor'),
 (2, 6, 'Member'),
 (3, 8, 'Member');

INSERT INTO events (id, organization_id, title, description, venue, start_time, end_time, registration_deadline, capacity, late_after_minutes, status, created_by, updated_by) VALUES
 -- happening today: registration closed, ready for check-in
 (1, 1, 'Tech Talk: Careers in Software',
     'Alumni share how they landed their first software jobs. Q&A to follow.',
     'AVR 1, Main Building',
     date_trunc('hour', now()) + interval '1 hour', date_trunc('hour', now()) + interval '3 hours', date_trunc('hour', now()),
     50, 15, 'Closed', 'msantos', 'msantos'),
 -- upcoming, open with free slots
 (2, 1, 'Intro to Web Development Workshop',
     'Hands-on workshop on HTML, CSS and ASP.NET Core. Bring your own laptop.',
     'Computer Lab 3',
     date_trunc('day', now()) + interval '7 days 9 hours', date_trunc('day', now()) + interval '7 days 12 hours', date_trunc('day', now()) + interval '6 days 17 hours',
     30, 15, 'Open', 'msantos', 'msantos'),
 -- upcoming, open and full (demonstrates the waitlist)
 (3, 1, 'Hackathon 2026 Orientation',
     'Team formation and rules briefing for this year''s hackathon. Limited slots.',
     'Innovation Hub',
     date_trunc('day', now()) + interval '3 days 13 hours', date_trunc('day', now()) + interval '3 days 15 hours', date_trunc('day', now()) + interval '2 days 17 hours',
     3, 10, 'Open', 'msantos', 'msantos'),
 -- draft (not visible to students yet)
 (4, 2, 'Engineering Leadership Summit',
     'Leadership training for class officers of the College of Engineering.',
     'Engineering Auditorium',
     date_trunc('day', now()) + interval '14 days 8 hours', date_trunc('day', now()) + interval '14 days 17 hours', date_trunc('day', now()) + interval '12 days 17 hours',
     100, 15, 'Draft', 'jreyes', 'jreyes'),
 -- finished, with attendance history
 (5, 3, 'Cultural Night 2026',
     'An evening of music, dance and theater performances.',
     'University Gymnasium',
     date_trunc('day', now()) - interval '10 days' + interval '18 hours', date_trunc('day', now()) - interval '10 days' + interval '21 hours', date_trunc('day', now()) - interval '11 days',
     0, 30, 'Completed', 'admin', 'admin');

INSERT INTO event_registrations (id, event_id, student_id, registration_code, status, registered_time) VALUES
 -- Tech Talk (today)
 (1,  1, 4, 'TT4K9QZP2A', 'Registered', now() - interval '3 days'),
 (2,  1, 5, 'TT7M3XWR8B', 'Registered', now() - interval '3 days'),
 (3,  1, 7, 'TT2H6LNC5D', 'Registered', now() - interval '2 days'),
 (4,  1, 9, 'TT9P4VJS3E', 'Registered', now() - interval '1 day'),
 -- Web Dev Workshop
 (5,  2, 4, 'WD3R8KTA6F', 'Registered', now() - interval '1 day'),
 (6,  2, 8, 'WD6Y2GMB4H', 'Registered', now() - interval '5 hours'),
 -- Hackathon Orientation (capacity 3 -> full, one waitlisted)
 (7,  3, 5, 'HK5N7QDC2J', 'Registered', now() - interval '2 days'),
 (8,  3, 7, 'HK8T3WEF9K', 'Registered', now() - interval '2 days'),
 (9,  3, 9, 'HK2L6ZRG7M', 'Registered', now() - interval '1 day'),
 (10, 3, 6, 'HK4B9XHN3P', 'Waitlisted', now() - interval '6 hours'),
 -- Cultural Night (completed)
 (11, 5, 4, 'CN7C2PJQ5R', 'Registered', now() - interval '15 days'),
 (12, 5, 6, 'CN3F8SKT6S', 'Registered', now() - interval '15 days'),
 (13, 5, 8, 'CN9G4UMV2T', 'Registered', now() - interval '14 days'),
 (14, 5, 9, 'CN5J6WNX8U', 'Registered', now() - interval '13 days');

INSERT INTO attendances (registration_id, check_in_time, check_out_time, status, remarks, recorded_by, recorded_time) VALUES
 (11, date_trunc('day', now()) - interval '10 days' + interval '17 hours 55 minutes', date_trunc('day', now()) - interval '10 days' + interval '21 hours', 'Present', NULL, 'admin', date_trunc('day', now()) - interval '10 days' + interval '17 hours 55 minutes'),
 (12, date_trunc('day', now()) - interval '10 days' + interval '18 hours 45 minutes', NULL, 'Late', 'Traffic', 'admin', date_trunc('day', now()) - interval '10 days' + interval '18 hours 45 minutes'),
 (13, date_trunc('day', now()) - interval '10 days' + interval '18 hours 5 minutes', date_trunc('day', now()) - interval '10 days' + interval '20 hours 30 minutes', 'Present', NULL, 'admin', date_trunc('day', now()) - interval '10 days' + interval '18 hours 5 minutes'),
 (14, NULL, NULL, 'Absent', NULL, 'admin', date_trunc('day', now()) - interval '10 days' + interval '21 hours');

-- Keep identity sequences ahead of the explicit ids used above
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT max(id) FROM users));
SELECT setval(pg_get_serial_sequence('organizations', 'id'), (SELECT max(id) FROM organizations));
SELECT setval(pg_get_serial_sequence('events', 'id'), (SELECT max(id) FROM events));
SELECT setval(pg_get_serial_sequence('event_registrations', 'id'), (SELECT max(id) FROM event_registrations));

COMMIT;
